language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10.0"
  - "8.3"
env:
  global:
    - CC_TEST_REPORTER_ID=22a90ce3d9efbb28ffb858e26e5f2d4b53f03186956eda3e50cf58e2d1754ddf
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make test
  - make coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
